services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Lemming\Imageoptimizer\:
    resource: '../Classes/*'

  Lemming\Imageoptimizer\Report\StatusReport:
    autoconfigure: true
